### ISSUE TITLE
[question] Should the pvc created in helm charts not be deleted upon deletion

### ISSUE THREAD

**Issue by St0rmingBr4in** [billimek/billimek-charts#168]
When deleting a chart maybe the created pvc must not be deleted.
That way the data would remain intact even if the chart is deleted.
It could be possible to use the `"helm.sh/resource-policy": keep` annotation to achieve this.

What do you think, should we use this annotation ?

**Comment by billimek** [comment]
If this were leveraged on the persistent volume objects, that would indeed prevent helm from removing them at uninstall time.

The side-effect would be that it could "lead to problems if using helm install --replace on a release that has already been uninstalled, but has kept resources." (from the [docs](https://helm.sh/docs/howto/charts_tips_and_tricks/#tell-helm-not-to-uninstall-a-resource)).

I wonder if it makes sense for folks to set that annotation as needed/desired instead of a default.  What do you think?

**Comment by St0rmingBr4in** [comment]
I would argue that fighting a little bit with helm is better than having your data be deleted by mistake. 
Maybe having something like this in values.yaml could be a good idea:
```yaml
persistence:
  config:
    enabled: true
    skipuninstall: false
```
The default value could be `true` if we feel avoiding losing data is more important than not having to clean the pvc by hand.
I will start working on the PR :)
