### ISSUE TITLE
InterDir Nzbget PVC

### ISSUE THREAD

**Issue by carpenike** [billimek/billimek-charts#171]
Looking to move my interdir off of the NFS share and onto a block device out of ceph. Should allow for a much faster processing time of small files with only the completed files being copied over to the NFS share that sonarr/radarr picks up.

Do you think it makes most sense to add this as a separate stanza in the nzbget chart or trying to use the `extravolumemounts:[]` block?

**Comment by billimek** [comment]
If `interdir` it were broken-out into it's own thing, it may be tricky if someone want's to combine say `downloads` and `interdir` with the same backing store.

I wonder if `extravolumemounts` is a good solve for this and generally speaking the rest of the volumes for the chart overall, instead of having separate distinct 'volumes' for `config`, `downloads`, `interdir`, etc?

**Comment by carpenike** [comment]
Yup i generally like that approach. I need to dig in and see how complicated it is to do a net new PVC rather than an existing claim when using extravolumemounts.

**Comment by billimek** [comment]
Closing, lets re-open if we need to revisit this!
