### ISSUE TITLE
How to install modem-stats

### ISSUE THREAD

**Issue by EasternPA** [billimek/billimek-charts#208]
Thank you for these charts. They make for a great opportunity to learn with a huge payoff at the end.

I had to jump through a few hoops to get modem-stats to install and run.

1) Install the bitnami repo (I have to think everyone has it by now)
2) helm install -n influxdb-influxdb bitnami/influxdb
3) Get the admin password by running the export ADMIN_PASSWORD command shown in the output. Copy it the clipboard.
4) helm install -n modem-stats billimek/modem-stats --set config.influxdb.username="admin",config.influxdb.password="<copied password>"

Only after following those steps did modem-stats successfully create. It took me a while to realize that modem-stats was looking for influxdb using the name "influxdb-influxdb". Then it failed on requiring a username. It finally said the table doesn't exist and it will try to create one. 

So, not sure if you'd like to beef up the docs a bit, but these are the hoops I had to jump through to get modem-stats to install.

Thanks!

**Comment by billimek** [comment]
Thanks for the info @EasternPA.  That was one of the very first charts I made and it is probably very lacking!  I think you may be the only other person using it other than myself too, given the model of the modem.

For what it's worth, I'm planning to refactor/re-create this modem stats approach using a prometheus exporter instead of influxdb (see #217).  Is this something that would interest you?

**Comment by billimek** [comment]
Closing, lets re-open if we need to revisit this!
