### ISSUE TITLE
Inconsistent Unifi Templates

### ISSUE THREAD

**Issue by jbrisko** [billimek/billimek-charts#3]
Hello

I am testing out your helm chart with a new deployment, and for my deployment I need to use the annotations in the services however they are only included in the template files for the GUI and Ingress. There is a configuration for them, and they are included in the values.yaml but they never get rendered into the services from the templates. Please let me know if you need any additional information.

Thanks for your work on this project!

**Comment by billimek** [comment]
Hi @jbrisko thanks for opening this.  I see what you describe.  I think the lack of deployment-level annotations is because the default `helm create` base template eschews deployment-level annotations.  

However, looking at other charts like grafana, we see that indeed there [is a deployment annotation](https://github.com/helm/charts/blob/master/stable/grafana/templates/deployment.yaml#L10-L13).

I'll add this, thanks!

**Comment by jbrisko** [comment]
Hey Jeff

Thanks for the reply. I think the deployment annotations would be worthwhile however I was referencing the different services. There are no annotations on the controller-svc.yaml or the stun-svc.yaml or the discovery-svc.yaml.

For my specific use case it would also be nice on the services to include the service.spec.externalTrafficPolicy as we are using load balancers to expose our services. 

Thanks again for your work on this.

**Comment by billimek** [comment]
@jbrisko nice catch, thank you!  This should be fixed now.

**Comment by jbrisko** [comment]
Thank you! It seems to be working great now. Thanks for your help!
