### ISSUE TITLE
Jackett and NZBHydra2 chart liveness and readyness probes

### ISSUE THREAD

**Issue by onedr0p** [billimek/billimek-charts#96]
I don't have more time to work on this tonight, so I'll create this issue to remind me.

nzbhydra2 is a Java Spring application and I might need to set the timeout a lot higher as it runs database migrations on start. Currently on Raspberry Pi this takes awhile.

Jackett also seems to take longer than a minute to start up as well.

Logs are showing the Container being killed.

@billimek do you have any suggestions, or do you think just adjusting the probes should do it, or maybe removing them?

**Edit:** I should have mentioned the probe PR didn't fix the issue, I'll need to figure out the best values...

**Comment by onedr0p** [comment]
I should have mentioned the probe PR didn't fix the issue, I'll need to figure out the best values...

**Comment by billimek** [comment]
@onedr0p I suggest we make the probes configurable.  See something similar done with the home-assistant chart [here](https://github.com/helm/charts/pull/19269).

It's most likely that the `initialDelaySeconds` needs to be bumped to something longer - maybe try 120?  Perhaps also make the `timeoutSeconds` 30 instead of 10?

Some workloads will have different startup times depending on the configuration and one value won't work for everyone which is why making it configurable is ideal.

**Comment by onedr0p** [comment]
The first point is spot on and actually I was looking at the HA chart last night working on this haha. I will open a PR to parameterize the probes on Tautulli, Ombi, Jackett, NZBHydra2, Radarr, qBittorrent and Sonarr. If there are other to apply we can tackle it later :)

Thanks for the feedback
